### ISSUE TITLE
Old combat values dont work

### ISSUE THREAD

**Issue by JHarris12345** [kernitus/BukkitOldCombatMechanics#350]
## Info

- Server version: 1.13.2
- OldCombatMechanics version: Latest
- Server log file:  https://pastebin.com/rR3Wq1Ek
- OldCombatMechanics config file:  https://pastebin.com/2wPUP2kB

## Problem Description
> 
My config shows that I should use 1.8 attack damage therefor sword attack damage is 8 and axe is 7. However my attack damage on the server is still 1.9 (7 for sword and 9 for axe)

**Comment by I-Al-Istannen** [comment]
Can you enable the debug mode in the config and see what damage it prints when hitting with a diamond sword/axe?

**Comment by JHarris12345** [comment]
https://gyazo.com/789e12d2c650b7a6c14c6ce94d134c96

Im not sure if Raw Damage: 9 means that is what it dealt. That was a diamond axe which should have damage 7

**Comment by I-Al-Istannen** [comment]
It set the damage to 7, some other plugin very likely modified it again. Do you have any idea which other plugin could modify it? If not I will throw together an event tracer build that should tell the whole story.

**Comment by JHarris12345** [comment]
The only plugin I can think of is PvPManager but that is to kill people for combat logs. You said the damage is set to 7, did it do 7 damage or was it MEANT to?

**Comment by I-Al-Istannen** [comment]
It originally did 9 damage, so OCM adjusted it to deal just 7. So you should have received 7 damage, unless another plugin interfered.

**Comment by JHarris12345** [comment]
I did receive the right damage. Why does it say the wrong value on the tool then?

**Comment by I-Al-Istannen** [comment]
Do you mean the vanilla damage values shown with extended tooltips?

If so:
That is because OCM does not modify the tools NBT damage data. It works by intercepting the damage event and dynamically calculating the correct value.

Anything else would be a bit of a nightmare, as *all tools in all worlds* would need to be changed whenever you modify the config. I suppose this could be done for each weapon once the user views it in some inventory, but I am not sure it is worth the effort?

**Comment by JHarris12345** [comment]
Ahh ok thanks
