### ISSUE TITLE
TNT/Creeper block drops.

### ISSUE THREAD

**Issue by shupliance** [kernitus/BukkitOldCombatMechanics#363]
I'm running an SMP server for my friends and I with a size of about 30 people. A few of my players have expressed extreme internal despair at the fact that, for whatever reason, this plugin causes all explosions to not drop the items they break, an addition in 1.14 they've gotten quite used to. It's horribly inconvenient to play without the ability to pick up every block broken, and i'd like to know if it's even possible for you to fix this, or if it's already a feature and i've missed it! Thank you.

(Spigot 1.15.2, OCM 1.7.4, the same issue persisted upon removal of every other plugin as well as pre-1.15.)

**Comment by I-Al-Istannen** [comment]
Hey,

are you sure that they are dropped *without having OCM installed* (i.e. disable *just* OCM on a test server with all your other plugins and settings and see if it works then)?
I can't think of a module causing that off the top of my head *and can not reproduce it myself* on 1.14 Paper, which is why I'm asking.

The minecraft wiki states that 
> Destroyed blocks from TNT or minecart with TNT explosions now have a 100% chance of dropping  as items.

Which doesn't quite seem to cover creepers?

Have a nice day!
