### ISSUE TITLE
Add support for Linux.

### ISSUE THREAD

**Issue by ncat1** [kernitus/BukkitOldCombatMechanics#366]
I was attempting to use this on Linux Mint, it doesn't even open, even after setting it to be executable.

**Comment by Madzahttr** [comment]
Something tells me that you ain't the sharpest tool in the shed.

This is a bukkit/spigot server plugin for minecraft. It is to be ran in the server, it is not an executable.

**Comment by Rayzr522** [comment]
@ncat1 this is not an executable program. In order to use this, you will need to run a Bukkit/Spigot server. More info about this can be found here: https://www.spigotmc.org/wiki/index/

This is not a standalone program and cannot be run as such, nor is it clientside, so it cannot be run without a server.
