### ISSUE TITLE
Tablist Colors & Prefixes buggy

### ISSUE THREAD

**Issue by Likqez** [kernitus/BukkitOldCombatMechanics#374]
## Information

* Server Version: https://i.imgur.com/aN5G0UP.png

* OldCombatMechanics version: 1.7.4

## Problem Description

> You claim that your plugin supports Tablist & Scoreboard Managing Plugins, but if I create my own little plugin just to modify the Tablist, it doesn't work quite as well. In my case, If I turn on `disable-player-collisions`, I can't see my own modified name, just the once from other players on the server.

 
### To Reproduce
1. Enable `disable-player-collisions`
2. Create your own plugin, which uses the Main Scoreboard to create Tablist prefixes etc.
3. Join with multiple clients

### Expected Behaviour
> Normal working tablist, with all players having their assigned colors etc.
### Actual Behaviour

* Player 1: https://i.imgur.com/EPgUEVv.png
* Player 2: https://i.imgur.com/L2r59nV.png

**Comment by OfficialCodex** [comment]
Yeah. I do have the same problemes. A fast fix is really needed!

**Comment by Rayzr522** [comment]
@Likqez source for your custom mini tablist plugin would be appreciated. we've tested this with various different tablist plugins which use packets to manage tablists, and those seem to be working fine. (although admittedly at this point I don't remember what tab list plugin we were testing this against, it's probably mentioned somewhere in a previous issue report since we changed our systems over due to an incompatibility with some popular tab plugin)

the main point of that compatibility statement is that we don't actually interfere with the use of scoreboards from a server-side perspective -- however, some client-side options might be overridden due to the fact that we trick the client into thinking they're on a different team. again, source for your mini tab list plugin would be appreciated, although I suspect I already know the answer to this problem.

my guess is, if you are using real server-side scoreboard teams to manage the tablist entries rather than using packets like a lot of popular tablist plugins do, that the server is sending the team packet to the client with your scoreboard team, only to have us override that with our team packet.

a potential fix would be to have our team packet utilities look at the ACTUAL server-side team of the player, copy over all other options other than collisions, and then send that merged packet to the client.

**Comment by Likqez** [comment]
@OfficialCodex If you are using paper you can easily fix this, by disabling `disable-player-collisions` in OCM and `enable-player-collisions` in your paper.yml. But for `enable-player-collisions = false` to be effective. All players need to be in A team, not necessary in the same!
