### ISSUE TITLE
Fishing rod knockback ineffective on jump

### ISSUE THREAD

**Issue by SladeHazard** [kernitus/BukkitOldCombatMechanics#400]
* Server Version: Paper 1.12.2

* OldCombatMechanics version: 1.8.1BETA but also happens in old versions

* OldCombatMechanics config file: https://pastebin.com/nSCBhpN4

## Problem Description
If you spam rod someone while he is running and jumping it pulls him towards you instead of giving knockback

1. Ask your opponent to jump and run at you
2. while he is doing that keep spam roding him
3. this will pull him towards you instead of cancelling

### Expected Behaviour
It doesn't give player knockback
### Actual Behaviour
It pulls the player

Video:
https://youtu.be/3eH-E1GqRSs

**Comment by kernitus** [comment]
Is the behaviour different with versions before OCM 1.8.0? Because I changed a lot of the fishing rod code since then

**Comment by SladeHazard** [comment]
> Is the behaviour different with versions before OCM 1.8.0? Because I changed a lot of the fishing rod code since then

no it's same in 1.7.4

**Comment by kernitus** [comment]
I'm not sure what I'm looking at in the video, I see it is giving damage, and thus should also be giving knockback. It is possible that the knockback is being counteracted by the fact that they're moving forward (resulting in being stopped), but it doesn't look like they're being pulled in

**Comment by SladeHazard** [comment]
> I'm not sure what I'm looking at in the video, I see it is giving damage, and thus should also be giving knockback. It is possible that the knockback is being counteracted by the fact that they're moving forward (resulting in being stopped), but it doesn't look like they're being pulled in

Please skip to 0:33 they are pulled in when they jump and run and someone hits them with a fishing rod so if someone is trying to keep someone away by a fishing rod and they just jump and run it will pull them towards the player this can be abused.

**Comment by kernitus** [comment]
It looks to me like them running and jumping is negating the effect of the knockback, and thus they're stopped in mid-air. Surely that's what _should_ be happening?

**Comment by SladeHazard** [comment]
> It looks to me like them running and jumping is negating the effect of the knockback, and thus they're stopped in mid-air. Surely that's what _should_ be happening?

yes that's what should be happening. but can you skip to the time stamps I provided in that they're being pulled. and btw i managed to fix this by using knockbackmasters plugin!

**Comment by kernitus** [comment]
That's not what I see in the video. Regardless, in order to do anything about this, we would need objective measurements/calculations of what you think the knockback should be like. You may find our current calculations [here](https://github.com/kernitus/BukkitOldCombatMechanics/blob/3857cb09383cacd201f35c340eed7f68f82e37fc/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java#L114), which are based on 1.8 knockback code.

**Comment by Rayzr522** [comment]
i'm hesitantly categorizing this as a can't reproduce + not enough info, since @SladeHazard has not provided any measurements or calculations that would be more capable than our current code. not actually convinced this is even a bug. feel free to re-open if you disagree @kernitus or if you have more info @SladeHazard
