### ISSUE TITLE
Cooldown not working for critical hits

### ISSUE THREAD

**Issue by Zlexz** [kernitus/BukkitOldCombatMechanics#438]
## Information

* Server Version:   Spigot 1.15.2

* OldCombatMechanics version: 1.8.1

* Server Log File: -

* OldCombatMechanics config file: default one

## Problem Description

Hit cooldown doesn't  work while critical hitting.

 
### To Reproduce
1. Critical hit a mob or player
2. Hit a mob or player normally
3. Compare hit speed

### Expected Behaviour
Same cooldown for normal and critical hits

### Actual Behaviour

Cooldown for critical hits is lower

https://www.youtube.com/watch?v=24foRUw3hMk&feature=youtu.be

**Comment by Rayzr522** [comment]
seems to be related to #443, and therefore by extension #19 

while investigating #443 i was never able to produce results as drastic as these, but rather seemed to be able to get higher-than-1.8 hit detection frequency whether I was critical hitting or not.

either way, this is not a bug, but rather a lack of a feature -- we don't have a way to configure hit detection frequency yet. if you have any more information about the technical aspects of how hit detection has changed, please drop a comment on #19 with that. otherwise you will sadly just have to wait until one of us has time to implement a hit detection module, or perhaps a community member will be so kind as to implement one for us.
