### ISSUE TITLE
Axes damage wont change

### ISSUE THREAD

**Issue by NLRicardoFTW** [kernitus/BukkitOldCombatMechanics#439]
I tried to change the diamond axe damage way lower, but every 2 hits the damage gets high incredible. Its not pvp worth it now, I want to be able to lower it.

**Comment by Rayzr522** [comment]
@NLRicardoFTW please follow the issue report template and provide (at the very least):

- OCM version
- OCM config
- Server version
- Server log file

additionally, turning `debug` mode on in the config and showing us some numbers from that while attacking a player would be massively beneficial since we can see all of the factors that are going into calculating final damage for each attack.

**Comment by Plixe** [comment]
Hi ! I don't have exactly the same problem, but **axes's attack attributes don't want change**. 
I try to craft, give or just get in the creative inventory and it's the same. I try to change the attack number in the config, but the attack damages for each axes stay the same:
- Wood/Gold: 7
- Stone/Iron/Diamond: 9
- Netherite: 10

I use **OCM 1.8.1** on **Paper 1.16.3 (231)**. In the config old attack damage is enabled and nothing in logs (even with debug).

**Comment by kernitus** [comment]
Do you know the label that shows in the inventory? Cause that won't change. It's the damage itself that does.
