### ISSUE TITLE
Cannot use offhand

### ISSUE THREAD

**Issue by Floofycandy9** [kernitus/BukkitOldCombatMechanics#444]
I have disabled the offhand-disable feature but I still cannot use my offhand. Is there any other thing I need to disable for it to work?

**Comment by Rayzr522** [comment]
@Floofycandy9 please follow the issue template when reporting issues. can't really help you much without a copy of your OCM config, the server & OCM version, and a server log file as well.

**Comment by Floofycandy9** [comment]
Alright sorry!

OCM Config: https://paste.helpch.at/ufowetutev.bash

Server Version: 1.16.1

Where do I find the OCM Version?

Latest Log: https://paste.helpch.at/azeyasepam.md

**Comment by Rayzr522** [comment]
`/version OldCombatMechanics` can show you the version, but I see from console logs that it's 1.8.1

looks like some of your log file was cut off, as it starts *after* `world_nether` loads, so going off of the limited context I have, I'm guessing this is caused by some other plugin you have. using the config you provided, Tuinity 1.16.1, and OCM 1.8.1, I was able to use my offhand slot without problems.

i'd recommend the following next steps:
- try [dev build 41](https://ci.rayzr.dev/job/OldCombatMechanics/41/) just for the heck of it, because it fixes some stuff anyways
- try running just your server JAR + OldCombatMechanics with your config to see if the problem is still present
- assuming that it's not, try cutting your plugin list in half and removing a half at a time until the problem goes away. then look at the half you just removed and re-add them one at a time (or re-add them half at a time)

just wondering, are you running Spigot, PaperSpigot, or Tuinity for your JAR?

**Comment by Floofycandy9** [comment]
I am running PaperSpigot

**Comment by Rayzr522** [comment]
interesting. thanks for the information. please let me know once you have completed the debugging steps I suggested, and if you can narrow down what plugin is causing this conflict -- if so, I'd like to either fix the conflict or make note of it somewhere
