### ISSUE TITLE
ProjectileKnockback doesn't work with CrackShot

### ISSUE THREAD

**Issue by telfrancesco** [kernitus/BukkitOldCombatMechanics#482]
## Problem
With egg / snowball ecc fix of OCM in 1.12.2 the knockback is broken in Vertical (With CrackShot's Guns have projectile like snowball, egg and Energy (entites))

## Proposed solution
Add an options in config.yml to customize the knockback in X and Y of projectile like Egg,Snowball ecc ecc

**Comment by MWHunter** [comment]
In the CrackShot source (which has a 5000 line main class), you can see on line 2213 in CSDirector.class:
snowball.setMetadata("projParentNode", (MetadataValue)new FixedMetadataValue((Plugin)CSDirector.this.plugin, parentNode));

Despite it's misleading name, this adds metadata to the projectiles fired from guns.  This may or may not be added to all of the plugin's projectiles, not sure because of how chaotic the source code is and it would need in-game testing.

A check for this metadata could solve the issue.

**Comment by kernitus** [comment]
This is not how this module works. It simply damages a player by a miniscule amount so they get knocked-back as a consequence. I don't see any difference at all between shooting someone with the module turned on or off. @telfrancesco what exactly do you mean by "the knockback is broken in Vertical"?
