### ISSUE TITLE
Configurable toggle messages

### ISSUE THREAD

**Issue by bobhenl** [kernitus/BukkitOldCombatMechanics#493]
## Problem
Hi, could we please translate [OCM] prefix of plugin?
![image](https://user-images.githubusercontent.com/18662086/108116235-8cd5dd80-709b-11eb-899a-80657ca953f3.png)

And also this message please.

## Proposed solution
Way to translate it.

**Comment by nikitushu2** [comment]
Why does it take so long to add such a small and essential fix?

**Comment by kernitus** [comment]
@nikitushu2 Please _never_ ask for an ETA on an open source project. What I do here is free work in the little spare time I have, and I have no contractual obligations to anyone. Furthermore, this is both **not** a fix, but a feature request, and **not** essential, because the plugin works just fine without it. If you really want this feature implemented quickly you can make it yourself; it's open source after all.
