### ISSUE TITLE
No lapis lazuli

### ISSUE THREAD

**Issue by Nelinka55** [kernitus/BukkitOldCombatMechanics#624]
Hello, I have an problem.
When I download OCB, lapis lazuli is not need in enchanting table and I don't know why.
I changed everything on enchanting table, but lapis lazuli wasn't need, or it was automatically added, is this bug of the plugin?

Thank you for your answer.
Nelinka55

**Comment by kernitus** [comment]
No, this is a feature of the plugin. If you don't want it, you just need to disable the `no-lapis-enchantments` in the config.

**Comment by Nelinka55** [comment]
no-lapis-enchantments:
  # Automatically adds lapis to enchantment tables upon opening
  enabled: false
  worlds: []
  # Whether to only allow this for players with oldcombatmechanics.nolapis permission
  usePermission: false



In the default setting is this set on ,,false", but I have problem when you don't need lapis lazuli and sword or anything else will enchant without lapis and I want to disable it, how can I do it?
![2022-09-14_22 39 16](https://user-images.githubusercontent.com/113387599/190257807-46a981b7-90fe-4259-8789-86e060003f57.png)

**Comment by kernitus** [comment]
Interesting. What are the exact versions of Spigot and the plugin you are using? The module shouldn't run at all if it is not enabled.

**Comment by Nelinka55** [comment]
I registered this problem a couple of years ago and thought it was just some tweak to the plugin, but as I've gotten older, I realized that it may be a bug that has been in the game for quite some time.
I have the latest version directly from the official Spigot site (1.11.0) on Minecraft version 1.19.2.
I started using your plugin back in 1.9 or 1.10 and I found this bug/problem already at that point, but I didn't know if it was a plugin tweak or a bug, so after a few years I decided to report it.

**Comment by kernitus** [comment]
This can't have been a plugin bug for that long, the module doesn't even get loaded if it's not enabled. What other plugins are you using? Do you have something like ProtocolSupport which could interfere?

**Comment by Nelinka55** [comment]
I have these plugins, ProtocolSupport I don't know, I never heard about it.
![obrazek](https://user-images.githubusercontent.com/113387599/202875962-493a080c-14a0-469a-9229-3083f1667482.png)

**Comment by rayzr522** [comment]
the behavior demonstrated in [the previous comment you shared](https://github.com/kernitus/BukkitOldCombatMechanics/issues/624#issuecomment-1247278877) is expected behavior as you are in creative mode:

survival | creative
-|-
![image](https://user-images.githubusercontent.com/15263431/227809001-108bcaab-a48c-44be-b7ae-d319418eefbc.png) | ![image](https://user-images.githubusercontent.com/15263431/227809011-3d9c12e0-8ccd-40c5-8251-d22deecb491f.png)

as you can see, when i'm in survival mode it does not allow me to enchant w/o lapis but when I'm in creative mode it does (you can see which mode I'm in based on my hotbar). these demo screenshots were taken without the plugin enabled on the server :) (fully disabled via Plugman)

you know that the plugin is enabled with `no-lapis-enchantments` turned on when you open the enchant GUI and see a full stack of lapis in the second slot (regardless of gamemode):

![image](https://user-images.githubusercontent.com/15263431/227809169-93286b0d-41e7-4e6b-8cdb-c0bd075e3790.png)

the reason this is necessary is actually because the _client_ will refuse to allow you to select an enchantment in survival unless you have lapis in the second slot, hence why we have to actually populate the slot via OCM in order for this module to work :)
