### ISSUE TITLE
A warn for a non NMS packet

### ISSUE THREAD

**Issue by Hermelijn15** [kernitus/BukkitOldCombatMechanics#632]
server version: paper 1.19.2
plugin version: 1.11.0
on a velocity network (maybe that is where the packet comes from?)
[22:13:41 WARN]: [OldCombatMechanics] Received a packet that is not NMS: class io.netty.buffer.PooledUnsafeDirectByteBuf PooledUnsafeDirectByteBuf(ridx: 0, widx: 5, cap: 256)
if i can provide more info please do let me know. this happens when a player joins the server

**Comment by kernitus** [comment]
It's entirely possible, is there more information printed at all? Do you have any plugins that might be modifying packets too?

**Comment by Hermelijn15** [comment]
For packets on the server itself i dont think anything should mess with it, only thing i can think of is viaversion?

**Comment by Hermelijn15** [comment]
also that is all it prints

**Comment by kernitus** [comment]
Hmm if you turn debug mode on in the config does it print anything more? It's definitely some other plugin directly writing packets

**Comment by Hermelijn15** [comment]
![image](https://user-images.githubusercontent.com/79708538/208319958-d4b82c85-18d0-4389-8ee6-3f46701125b7.png)
this is all that i see

**Comment by Hermelijn15** [comment]
I do assume that it is not a big deal if it is caused by a different plugin?

**Comment by I-Al-Istannen** [comment]
That just means that OCM detected that some plugin is injecting arbitrary bytes into the player connection instead of server packets. OCM is not able to inspect and rewrite those (as they are no packets), so packet-based fixes like no-collision or sound/particle effect cancellations might no longer work correctly.

Chances are nothing will happen, but OCM might also no longer function properly. That depends on what plugin is injecting random bytes and for what reason.
