### ISSUE TITLE
Still hearing attack sounds

### ISSUE THREAD

**Issue by ImVentiix** [kernitus/BukkitOldCombatMechanics#651]
This is my config: https://pastebin.com/PnFVsEcm

Why do i still hear the Attack sounds? im using paper-1.19.3-407.jar

**Comment by SKILLETTON2K** [comment]
Same here

**Comment by rayzr522** [comment]
@ImVentiix 1.19 compatibility for the attack sounds module has not been officially released yet but has been fixed in the [latest dev builds](https://ci.rayzr.dev/job/OldCombatMechanics/), we are working on getting a new stable release out but in the meantime please use the dev build :)

@SKILLETTON2K please try the latest dev build as well. if you're still having issues with player collisions with the dev build, please open a separate issue & fill out the issue template with the requested details. thanks!
