### ISSUE TITLE
Changing plugin version resets the config file

### ISSUE THREAD

**Issue by LouisDcg** [kernitus/BukkitOldCombatMechanics#659]
## Information
* Server Version: Paper 1.12.2

* OldCombatMechanics version: 1.12.0

* Server Log File: 
``` [19:37:41] [Server thread/INFO]: Enabling OldCombatMechanics v1.12.0
[19:37:41] [Server thread/WARN]: Config version does not match, backing up old config and creating a new one
[19:37:41] [Server thread/INFO]: Config file generated
[19:37:41] [Server thread/INFO]: OldCombatMechanics v1.12.0 has been enabled
```

## Problem Description
When I change the OldCombatMechanics version of the plugin (for example, from 1.11.0 to 1.12.0), the server generates a new config file because it does not matching with config version. Therefore, I have to set all the config again...
It was already like that with previous versions of the plugin.

### Expected Behaviour
The config should not change, or changing version should change (or reset ?) only the things concerned by the update.

(I don't know if it is normal...)

**Comment by kernitus** [comment]
This is expected behaviour. From version 1.12.0 of OldCombatMechanics onwards, I added an auto-updater which is capable of transferring the old config values to a new config in-place. However, this needs Spigot 1.18.1 or above as the functionality to do so is not present in older versions. You appear to be running Paper 1.12, meaning the only option is to backup the old config and replace it with a new one.

**Comment by kernitus** [comment]
@LouisDcg Just letting you know that in [test version 149](https://ci.rayzr.dev/job/OldCombatMechanics/149/) and above there is now an option to force config updating called ``force-below-1-18-1-config-upgrade``. This will of course remove all comments if enabled in version below Spigot 1.18.1 when the config is upgraded.
