### ISSUE TITLE
Pre-1.9 Hitbox

### ISSUE THREAD

**Issue by Wykaz** [kernitus/BukkitOldCombatMechanics#69]
I'm sure there's a change of hitbox to 1.9+. https://www.youtube.com/watch?v=kaXnQaa9vMw&edit=vd
A developer of a large french server made a video and he successfully re-exchange the hitbox as in 1.8. https://www.youtube.com/watch?v=dfGHN93dGVM

**Comment by FrenzyCake** [comment]
Agreed, this should be implented into the plug-in!

**Comment by x9nico** [comment]
We need this!

**Comment by kernitus** [comment]
I believe this is only possible server-side by doing our own calculations with a BoundingBox around a player, but the player ping and the network delay need to be taken into account before checking. I do not think this is worth it, especially because it can be inaccurate, computationally expensive and not directly visible to the players.
